# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='auth.proto',
    package='',
    syntax='proto3',
    serialized_options=b'\n\017com.funnify.app',
    serialized_pb=b'\n\nauth.proto\"\x19\n\x06Result\x12\x0f\n\x07success\x18\x01 \x01(\x08\"G\n\x13\x41uthenticateRequest\x12\x0f\n\x07idToken\x18\x01 \x01(\t\x12\x1f\n\x08provider\x18\x02 \x01(\x0e\x32\r.AuthProvider\"C\n\x14\x41uthenticateResponse\x12\x17\n\x06result\x18\x01 \x01(\x0b\x32\x07.Result\x12\x12\n\nsessionKey\x18\x02 \x01(\t*(\n\x0c\x41uthProvider\x12\n\n\x06GOOGLE\x10\x00\x12\x0c\n\x08\x46\x41\x43\x45\x42OOK\x10\x01\x32M\n\x0e\x46unnifyService\x12;\n\x0c\x61uthenticate\x12\x14.AuthenticateRequest\x1a\x15.AuthenticateResponseB\x11\n\x0f\x63om.funnify.appb\x06proto3'
)

_AUTHPROVIDER = _descriptor.EnumDescriptor(
    name='AuthProvider',
    full_name='AuthProvider',
    filename=None,
    file=DESCRIPTOR,
    values=[
        _descriptor.EnumValueDescriptor(
            name='GOOGLE', index=0, number=0,
            serialized_options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='FACEBOOK', index=1, number=1,
            serialized_options=None,
            type=None),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=183,
    serialized_end=223,
)
_sym_db.RegisterEnumDescriptor(_AUTHPROVIDER)

AuthProvider = enum_type_wrapper.EnumTypeWrapper(_AUTHPROVIDER)
GOOGLE = 0
FACEBOOK = 1

_RESULT = _descriptor.Descriptor(
    name='Result',
    full_name='Result',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='success', full_name='Result.success', index=0,
            number=1, type=8, cpp_type=7, label=1,
            has_default_value=False, default_value=False,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=14,
    serialized_end=39,
)

_AUTHENTICATEREQUEST = _descriptor.Descriptor(
    name='AuthenticateRequest',
    full_name='AuthenticateRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='idToken', full_name='AuthenticateRequest.idToken', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='provider', full_name='AuthenticateRequest.provider', index=1,
            number=2, type=14, cpp_type=8, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=41,
    serialized_end=112,
)

_AUTHENTICATERESPONSE = _descriptor.Descriptor(
    name='AuthenticateResponse',
    full_name='AuthenticateResponse',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='result', full_name='AuthenticateResponse.result', index=0,
            number=1, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='sessionKey', full_name='AuthenticateResponse.sessionKey', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=114,
    serialized_end=181,
)

_AUTHENTICATEREQUEST.fields_by_name['provider'].enum_type = _AUTHPROVIDER
_AUTHENTICATERESPONSE.fields_by_name['result'].message_type = _RESULT
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
DESCRIPTOR.message_types_by_name['AuthenticateRequest'] = _AUTHENTICATEREQUEST
DESCRIPTOR.message_types_by_name['AuthenticateResponse'] = _AUTHENTICATERESPONSE
DESCRIPTOR.enum_types_by_name['AuthProvider'] = _AUTHPROVIDER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
    'DESCRIPTOR': _RESULT,
    '__module__': 'auth_pb2'
    # @@protoc_insertion_point(class_scope:Result)
})
_sym_db.RegisterMessage(Result)

AuthenticateRequest = _reflection.GeneratedProtocolMessageType('AuthenticateRequest', (_message.Message,), {
    'DESCRIPTOR': _AUTHENTICATEREQUEST,
    '__module__': 'auth_pb2'
    # @@protoc_insertion_point(class_scope:AuthenticateRequest)
})
_sym_db.RegisterMessage(AuthenticateRequest)

AuthenticateResponse = _reflection.GeneratedProtocolMessageType('AuthenticateResponse', (_message.Message,), {
    'DESCRIPTOR': _AUTHENTICATERESPONSE,
    '__module__': 'auth_pb2'
    # @@protoc_insertion_point(class_scope:AuthenticateResponse)
})
_sym_db.RegisterMessage(AuthenticateResponse)

DESCRIPTOR._options = None

_FUNNIFYSERVICE = _descriptor.ServiceDescriptor(
    name='FunnifyService',
    full_name='FunnifyService',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=225,
    serialized_end=302,
    methods=[
        _descriptor.MethodDescriptor(
            name='authenticate',
            full_name='FunnifyService.authenticate',
            index=0,
            containing_service=None,
            input_type=_AUTHENTICATEREQUEST,
            output_type=_AUTHENTICATERESPONSE,
            serialized_options=None,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_FUNNIFYSERVICE)

DESCRIPTOR.services_by_name['FunnifyService'] = _FUNNIFYSERVICE

# @@protoc_insertion_point(module_scope)
